version: '3.8'

services:
  backend:
    build: ./backend
    container_name: chat-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - chat-network

  frontend:
    build: ./frontend
    container_name: chat-frontend
    ports:
      - "3001:3001"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    depends_on:
      - backend
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge