version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    depends_on:
      - backend
    networks:
      - chat-network

  backend:
    image: your-backend-image:latest  # Replace with your actual backend image
    ports:
      - '3000:3000'
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge